version: 0.2
os: ubuntu
phases:
  install:
    commands:
      - echo nothing to do in install phase
  pre_build:
    commands:
      - echo nothing to do in install phase
  build:
    commands:
      - echo nothing to do in install phase
  post_build:
    commands:
      - echo nothing to do in install phase